import { Item } from "../../types";

export const items: Item[] = [
    {
        id: "b47326d9-cedd-4af4-a680-af84d47bbe88",
        name: "Heartstring Pendant",
        description:
            "Increases Empathy XP during acts of kindness or understanding",
        affectedSkill: "Empathy",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "812c5895-cf7b-4b4f-90f4-dcfee5d892b7",
        name: "Gloves of Gentle Touch",
        description: "Boosts Empathy XP when helping others",
        affectedSkill: "Empathy",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "7382e991-c393-4baf-bb60-28a700f92dc2",
        name: "Tears of Compassion Vial",
        description: "Doubles Empathy XP when listening to others concerns",
        affectedSkill: "Empathy",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "eb9263eb-c390-42e9-a7ee-630336d0a884",
        name: "Whispering Shell",
        description:
            "Enhances Empathy XP for effective communication in sensitive situations",
        affectedSkill: "Empathy",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "0e97fb35-63df-4793-88f8-f90071b1183f",
        name: "Cloak of Comfort",
        description: "Grants extra Empathy XP when supporting someone in need",
        affectedSkill: "Empathy",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "306469ca-5582-433d-90bc-b436aa8fc08a",
        name: "Iron Will Bracers",
        description: "Increases Endurance XP during long or difficult tasks",
        affectedSkill: "Endurance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "9616e141-c08a-4d3d-b371-7a5c3d64f6fc",
        name: "Endless Stamina Elixir",
        description: "Boosts Endurance XP for physical challenges",
        affectedSkill: "Endurance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "2262159f-fb41-4eeb-bbda-992d32210d31",
        name: "Resilience Band",
        description:
            "Doubles Endurance XP when facing mental or physical strain",
        affectedSkill: "Endurance",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "66d316d0-ef21-4721-9554-0351e2f075ba",
        name: "Stoneheart Amulet",
        description: "Enhances Endurance XP for tasks requiring persistence",
        affectedSkill: "Endurance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "d36181a4-4872-4ae7-964d-408c24ed1728",
        name: "Sand of Time Hourglass",
        description:
            "Grants extra Endurance XP for completing prolonged activities",
        affectedSkill: "Endurance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "9b5b5fb7-5a71-48a3-ab78-88138dbbb808",
        name: "Golden Apple",
        description: "Boosts Nutrition XP when making healthy food choices",
        affectedSkill: "Nutrition",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "421bf555-5f11-422e-9664-1991a38355f2",
        name: "Herbalist's Satchel",
        description: "Increases Nutrition XP from meal planning or preparation",
        affectedSkill: "Nutrition",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "4c31d74d-f1f7-4de6-a105-27f6647ae678",
        name: "Elixir of Vitality",
        description:
            "Doubles Nutrition XP when experimenting with new, healthy recipes",
        affectedSkill: "Nutrition",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "0b43db8f-1fee-4a63-9f98-24206bf6ca34",
        name: "Seed of Renewal",
        description: "Enhances Nutrition XP when focusing on balanced eating",
        affectedSkill: "Nutrition",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "f482af87-3e72-45e6-974d-17ee36b7edde",
        name: "Chef's Charm",
        description: "Grants extra Nutrition XP for cooking nutritious meals",
        affectedSkill: "Nutrition",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "6bdc3f0c-0cc6-417e-9944-178bbe5384c0",
        name: "Dreamcatcher Charm",
        description:
            "Increases Sleep Hygiene XP from following a bedtime routine",
        affectedSkill: "Sleep Hygiene",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "214b2ceb-c971-4d3f-9056-373925646bf5",
        name: "Pillow of Serenity",
        description: "Boosts Sleep Hygiene XP when getting a full night’s rest",
        affectedSkill: "Sleep Hygiene",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "3e85f8ca-518b-414d-8cb9-7e32cba2c544",
        name: "Nightshade Elixir",
        description:
            "Doubles Sleep Hygiene XP for maintaining consistent sleep patterns",
        affectedSkill: "Sleep Hygiene",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "154c1699-7b2b-4265-b6b3-335d7e64fed4",
        name: "Lullaby Amulet",
        description:
            "Enhances Sleep Hygiene XP when practicing relaxation techniques",
        affectedSkill: "Sleep Hygiene",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "58f3c146-5413-4c62-8f6b-45ed48f769f7",
        name: "Moonlit Blanket",
        description: "Grants extra Sleep Hygiene XP for achieving deep sleep",
        affectedSkill: "Sleep Hygiene",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "bd04d7f9-75aa-499d-9e4b-65a420fa0835",
        name: "Coin of Prosperity",
        description: "Increases Finance XP when budgeting or saving money.",
        affectedSkill: "Finance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "3def8a72-5c77-40dc-b6eb-0a0f84d5bef2",
        name: "Ledger of Wealth",
        description: "Boosts Finance XP for tracking expenses.",
        affectedSkill: "Finance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "6048358e-bf7e-4593-9820-79729c4b41f1",
        name: "Golden Piggy Bank",
        description: "Doubles Finance XP when reaching savings goals.",
        affectedSkill: "Finance",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "5cc3165a-2a0d-4f7d-8a2e-b82c51a1c89a",
        name: "Investor's Crystal",
        description: "Enhances Finance XP for wise investments.",
        affectedSkill: "Finance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "be765d10-0a27-45d5-a5e6-830ec6a1bb48",
        name: "Purse of Plenty",
        description:
            "Grants extra Finance XP for practicing financial discipline.",
        affectedSkill: "Finance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "61495af9-4093-4a18-ace1-bc9c59ec5784",
        name: "Hourglass of Efficiency",
        description: "Boosts Time Management XP for meeting deadlines.",
        affectedSkill: "Time Management",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "d010d082-0902-4bf2-985e-90a437d52a24",
        name: "Chronos Ring",
        description: "Increases Time Management XP when planning your day.",
        affectedSkill: "Time Management",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "86851d94-cc91-4e0e-86f8-18788c2b1807",
        name: "Planner’s Pen",
        description: "Doubles Time Management XP for effective scheduling.",
        affectedSkill: "Time Management",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "30128be7-75fa-488d-9645-fa80d6155942",
        name: "Sands of Punctuality",
        description: "Enhances Time Management XP for arriving on time.",
        affectedSkill: "Time Management",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "922d9038-0288-44a9-a290-2b6f5e164d7b",
        name: "Clockwork Amulet",
        description:
            "Grants extra Time Management XP for optimizing your routine.",
        affectedSkill: "Time Management",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "ec83588f-7fa0-4099-b504-8b7586d06ab3",
        name: "Mind’s Eye Crystal",
        description: "Increases Mental Clarity XP when meditating or focusing.",
        affectedSkill: "Mental Clarity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "d479d35a-49fd-4d2f-8bdc-bb0b8e536fb0",
        name: "Fog Clearing Amulet",
        description: "Boosts Mental Clarity XP for practicing mindfulness.",
        affectedSkill: "Mental Clarity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "dfaaac28-01f9-45fb-8eb8-41668ccae793",
        name: "Elixir of Insight",
        description: "Doubles Mental Clarity XP during problem-solving tasks.",
        affectedSkill: "Mental Clarity",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "df77aabb-5ea4-4773-a0c9-b808b33a71d1",
        name: "Clarity Stone",
        description: "Enhances Mental Clarity XP for mental exercises.",
        affectedSkill: "Mental Clarity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "180acfcc-8566-4cf6-83f6-5fca6e458ac9",
        name: "Wisdom Herb",
        description:
            "Grants extra Mental Clarity XP when studying or learning.",
        affectedSkill: "Mental Clarity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "ae0016a8-59dd-464e-a24c-7374480194d6",
        name: "Muse's Quill",
        description:
            "Increases Creativity XP during artistic or creative tasks.",
        affectedSkill: "Creativity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "c11234cf-9267-441e-9f18-a2117c3e9d55",
        name: "Imagination Ink",
        description: "Boosts Creativity XP when brainstorming new ideas.",
        affectedSkill: "Creativity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "ec112f5e-b49a-4a84-a11c-3f57091d2657",
        name: "Canvas of Creation",
        description: "Doubles Creativity XP when working on an art project.",
        affectedSkill: "Creativity",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "86c28706-984d-474c-b19a-e56e51d0affd",
        name: "Inspiration Crystal",
        description:
            "Enhances Creativity XP for exploring new creative outlets.",
        affectedSkill: "Creativity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "f0651fdf-4706-4871-9c65-d47583da3830",
        name: "Spark of Genius",
        description:
            "Grants extra Creativity XP for completing a creative challenge.",
        affectedSkill: "Creativity",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "7ef82c71-163a-4970-a3cc-c67749a4dc09",
        name: "Sage's Scroll",
        description:
            "Increases Wisdom XP from reading or learning experiences.",
        affectedSkill: "Wisdom",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "6409d487-f175-4941-9ff2-782185b430d8",
        name: "Philosopher’s Stone",
        description: "Boosts Wisdom XP when reflecting on past decisions.",
        affectedSkill: "Wisdom",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "34643224-7ce7-4d94-822a-5ddd2989544b",
        name: "Oracle’s Orb",
        description: "Doubles Wisdom XP for offering advice or guidance.",
        affectedSkill: "Wisdom",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "27e967ac-c010-4d91-9301-dc9497c07ce2",
        name: "Ancient Tome",
        description: "Enhances Wisdom XP for studying or seeking knowledge.",
        affectedSkill: "Wisdom",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "b81ebdb5-0fac-4595-a6b7-e84950db761f",
        name: "Elder’s Amulet",
        description: "Grants extra Wisdom XP when making thoughtful decisions.",
        affectedSkill: "Wisdom",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "c4767cff-53c7-4627-8bd0-0d6f87a20447",
        name: "Binary Band",
        description:
            "Increases Tech Proficiency XP when learning new software or skills.",
        affectedSkill: "Tech Proficiency",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "10b02a59-a535-4395-8b22-04266fc0bbdc",
        name: "Circuit of Mastery",
        description:
            "Boosts Tech Proficiency XP for coding or technical tasks.",
        affectedSkill: "Tech Proficiency",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "72dd00f0-376b-4488-929b-5d4409830d1e",
        name: "Data Crystal",
        description:
            "Doubles Tech Proficiency XP for troubleshooting or solving tech issues.",
        affectedSkill: "Tech Proficiency",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "6cee1f0e-6578-4536-92ba-a1f3b47c0cee",
        name: "Hacker’s Glove",
        description:
            "Enhances Tech Proficiency XP for working with complex technology.",
        affectedSkill: "Tech Proficiency",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "4089b625-e961-4559-819a-de16d3928735",
        name: "Cyber Amulet",
        description:
            "Grants extra Tech Proficiency XP when staying current with tech trends.",
        affectedSkill: "Tech Proficiency",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "83cf35d5-4017-4cb2-8827-8d87e3241e37",
        name: "Painter’s Palette",
        description: "Increases Art XP during painting or drawing activities.",
        affectedSkill: "Art",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "0650c896-9918-4423-9493-c7153541ff6e",
        name: "Sculptor's Chisel",
        description: "Boosts Art XP for working with physical mediums.",
        affectedSkill: "Art",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "a5bed988-9735-4357-864c-769a2f4d3e67",
        name: "Brush of Brilliance",
        description: "Doubles Art XP for completing an art project.",
        affectedSkill: "Art",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "9d16a4a8-cae1-4bbf-b4d1-cdb8cb2900bb",
        name: "Artisan's Easel",
        description: "Enhances Art XP when practicing new techniques.",
        affectedSkill: "Art",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "c6252a47-39ae-4254-8032-b24954bebadb",
        name: "Vivid Ink",
        description:
            "Grants extra Art XP for experimenting with colors and forms.",
        affectedSkill: "Art",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "b83e1c04-a8a0-4941-bc50-eb2bec78547c",
        name: "Lyricist's Lute",
        description: "Increases Writing XP for crafting songs or poems.",
        affectedSkill: "Writing",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "91960baa-541e-47b9-951f-1ad03a3cf696",
        name: "Rhymebook",
        description: "Boosts Writing XP when writing lyrics or rhymes.",
        affectedSkill: "Writing",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "a9d58689-6335-463f-8abd-8883b1c956a7",
        name: "Poet's Quill",
        description: "Doubles Writing XP for completing a poetry collection.",
        affectedSkill: "Writing",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "b1464393-70bc-4e34-b32d-3082c52907b8",
        name: "Novelist's Notebook",
        description: "Enhances Writing XP for working on a novel or story.",
        affectedSkill: "Writing",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "cb8ec8cc-67fe-4154-afdc-b88457dc824a",
        name: "Storyteller's Charm",
        description: "Grants extra Writing XP for creative writing challenges.",
        affectedSkill: "Writing",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "a1784835-dfca-425f-809f-9bcd1799d626",
        name: "Harmonic Tuning Fork",
        description: "Increases Music XP during practice or performance.",
        affectedSkill: "Music",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "547109d6-121b-48ae-97ea-d00509f78afb",
        name: "Composer's Baton",
        description: "Boosts Music XP for creating or composing music.",
        affectedSkill: "Music",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "956784b2-937d-44a4-bfd4-0f8d8621ccf1",
        name: "Melody Crystal",
        description: "Doubles Music XP for learning a new instrument.",
        affectedSkill: "Music",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "af98dd6c-a54c-4634-8e25-eed1a74957d8",
        name: "Resonance String",
        description: "Enhances Music XP when playing or composing.",
        affectedSkill: "Music",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "befa8545-719a-4302-80db-433adc2a4476",
        name: "Musician's Muse",
        description: "Grants extra Music XP for performing in front of others.",
        affectedSkill: "Music",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "9038d15a-d87b-453c-a9f7-65bca7434b62",
        name: "Silver-Tongued Amulet",
        description: "Boosts Charisma XP when interacting with others",
        affectedSkill: "Charisma",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "77506c09-1f96-4d15-9792-bde1865aefa3",
        name: "Cloak of Confidence",
        description:
            "Grants extra Charisma XP by increasing the players confidence",
        affectedSkill: "Charisma",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "e2027b54-9dd6-4a8e-a21a-88df8ff6e93a",
        name: "Charm Bracelet",
        description: "Increases Charisma XP by charming others",
        affectedSkill: "Charisma",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "f287d3f6-3c0c-4624-9dda-bc05fa9d0aa7",
        name: "Voice of Persuasion Scroll",
        description: "Doubles Charisma XP by convincing others",
        affectedSkill: "Charisma",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "7720aed3-6dfc-4764-9d58-a96d18e71ec5",
        name: "Enchanted Mirror",
        description: "Reflects self-assurance, boosting Charisma XP",
        affectedSkill: "Charisma",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "8549c7ce-2cf7-4d1a-903d-c704a0e717b4",
        name: "Toolkit of Precision",
        description:
            "Grants extra Maintenance XP by providing the right tools for the job",
        affectedSkill: "Maintenance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "a4cf8e88-5669-470e-80cf-faeaaf14c835",
        name: "Rugged Work Gloves",
        description: "Increases Maintenance XP due to physical protection",
        affectedSkill: "Maintenance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "ead01902-f2f5-42a7-8934-c23905d8a24c",
        name: "Oil of Efficiency",
        description: "Boosts Maintenance XP by being more efficient",
        affectedSkill: "Maintenance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "b608deab-a74e-45c5-bc7e-b31eb5937838",
        name: "Blueprints of Mastery",
        description: "Doubles Maintenance XP by planning ahead",
        affectedSkill: "Maintenance",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "0ec5b8e0-4bad-4dbf-b1d5-acbcf84173d0",
        name: "Hammer of Habit",
        description: "Increases Maintenance XP by developing good habits",
        affectedSkill: "Maintenance",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "141e9c09-8948-4e35-abcb-bb949dd441be",
        name: "Titan's Gauntlets",
        description: "Making heavy lifting easier, thus boosting Strength XP",
        affectedSkill: "Strength",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "adb6b970-a6fb-42ec-9729-d8254c9bf68b",
        name: "Boulderbreaker",
        description: "Increases Strength XP by breaking boulders",
        affectedSkill: "Strength",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "fbdf7442-c2ee-4e8b-8be7-9b80711fab7f",
        name: "Ironclad Boots",
        description: "Grants extra Strength XP for performing leg exercises",
        affectedSkill: "Strength",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "b3fccdd4-d257-405e-b380-65d75750d2bb",
        name: "Elixir of Might",
        description:
            "Doubles Strength XP for weight training or resistance workouts",
        affectedSkill: "Strength",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "ea944ed1-09f8-40c2-a830-e17243edec20",
        name: "Shield of Fortitude",
        description: "Increases Strength XP for tasks that require resilience",
        affectedSkill: "Strength",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "b6c8ab39-63df-498d-ab2f-3d3608dab854",
        name: "Potion of Versatility",
        description: "Boosts XP in any skill",
        affectedSkill: "All",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "2b109787-8d4a-4a9f-9f72-a356f4ed407d",
        name: "Ring of Focus",
        description: "Increases the players focus for more XP gains",
        affectedSkill: "All",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "03f79440-0b19-4d0d-8042-44d8c07e0306",
        name: "Scroll of Rediscovery",
        description:
            "Doubles XP for a random skill the player hasn't practiced in a while",
        affectedSkill: "All",
        modifier: "*2",
        cost: 2000,
    },
    {
        id: "15effd15-1c57-404c-b960-ffbcfe9defc5",
        name: "Amulet of Balance",
        description: "Balances XP across all skills, favoring the lowest",
        affectedSkill: "All",
        modifier: "+1",
        cost: 1000,
    },
    {
        id: "5c22b4b5-d1dc-4f45-994a-3bf711cd6c4a",
        name: "Chalice of Reflection",
        description:
            "Grants a bonus to the skill that the player most recently neglected",
        affectedSkill: "All",
        modifier: "+1",
        cost: 1000,
    },
];
